const propertie= [
      {
        "user_id": "user123",
        "imageURL": "https://archello.com/thumbs/images/2022/03/18/tbs-10-c-randhir-singh.1647614802.6646.jpg?fit=crop&w=1260",
        "type": "sale",
        "location": "New York",
        "address": "123 Main Street, New York, NY",
        "rooms": 6,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 2000,
        "price": 800000,
        "category":"Popular"
      },
      {
        "user_id": "user456",
        "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-08.1647603038.576.jpg?fit=crop&auto=compress",
        "type": "rent",
        "location": "New York",
        "address": "456 Elm Avenue, New York, NY",
        "rooms": 4,
        "bedrooms": 2,
        "bathrooms": 1,
        "size_sqft": 1200,
        "price": 2500,
        "category":"Popular"
      },
      {
        "user_id": "user789",
        "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-09.1647603038.9821.jpg?fit=crop&auto=compress",
                "type": "lease",
        "location": "New York",
        "address": "789 Oak Street, New York, NY",
        "rooms": 5,
        "bedrooms": 2,
        "bathrooms": 2,
        "size_sqft": 1500,
        "price": 3500
      },
      {
        "user_id": "user101",
        "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-10.1647603039.3675.jpg?fit=crop&auto=compress",
                "type": "sale",
        "location": "London",
        "address": "10 Baker Street, London, W1U",
        "rooms": 7,
        "bedrooms": 4,
        "bathrooms": 3,
        "size_sqft": 2500,
        "price": 1200000
      },
      {
        "user_id": "user202",
        "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Burj%20in%20all%20its%20glory%20!.jpg",
                "type": "rent",
        "location": "London",
        "address": "20 Oxford Road, London, SW1A",
        "rooms": 3,
        "bedrooms": 1,
        "bathrooms": 1,
        "size_sqft": 800,
        "price": 2000,
        "category":"Popular"
      },
      {
        "user_id": "user303",
        "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/toyko-sky-tree.jpg",
                "type": "lease",
        "location": "London",
        "address": "30 Regent Street, London, SW1Y",
        "rooms": 6,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 1800,
        "price": 3500
      },
      {
        "user_id": "user404",
        "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Makkah%20Royal%20Clock%20Tower.jpg",
        "type": "sale",
        "location": "Mumbai",
        "address": "123 Palm Avenue, Mumbai, MH",
        "rooms": 5,
        "bedrooms": 3,
        "bathrooms": 2,
        "size_sqft": 1600,
        "price": 900000
      },
      {
        "user_id": "user505",
        "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-09.1647603038.9821.jpg?fit=crop&auto=compress",
        "type": "rent",
        "location": "Mumbai",
        "address": "456 Sea View Road, Mumbai, MH",
        "rooms": 4,
        "bedrooms": 2,
        "bathrooms": 1,
        "size_sqft": 1100,
        "price": 30000,
        "category":"Popular"
      },
      {
        "user_id": "user606",
        "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-08.1647603038.576.jpg?fit=crop&auto=compress",
              "type": "lease",
        "location": "Mumbai",
        "address": "789 Hillside Lane, Mumbai, MH",
        "rooms": 3,
        "bedrooms": 1,
        "bathrooms": 1,
        "size_sqft": 900,
        "price": 20000,
        "category":"Popular"
      },
          {
            "user_id": "user707",
            "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/toyko-sky-tree.jpg",
            "type": "sale",
            "location": "New York",
            "address": "456 Park Avenue, New York, NY",
            "rooms": 7,
            "bedrooms": 4,
            "bathrooms": 3,
            "size_sqft": 2200,
            "price": 950000
          },
          {
            "user_id": "user808",
            "imageURL": "https://archello.com/thumbs/images/2022/03/18/tbs-10-c-randhir-singh.1647614802.6646.jpg?fit=crop&w=1260",
            "type": "rent",
            "location": "New York",
            "address": "789 Lakeview Drive, New York, NY",
            "rooms": 5,
            "bedrooms": 3,
            "bathrooms": 2,
            "size_sqft": 1800,
            "price": 2800
          },
          {
            "user_id": "user909",
            "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Lotte%20World%20Tower%20-%20modlar_com.jpg",
            "type": "lease",
            "location": "New York",
            "address": "101 River Road, New York, NY",
            "rooms": 6,
            "bedrooms": 2,
            "bathrooms": 2,
            "size_sqft": 1600,
            "price": 3600
          },
          {
            "user_id": "user111",
            "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Makkah%20Royal%20Clock%20Tower.jpg",
            "type": "sale",
            "location": "London",
            "address": "40 High Street, London, W1S",
            "rooms": 8,
            "bedrooms": 5,
            "bathrooms": 4,
            "size_sqft": 3000,
            "price": 1500000,
            "category":"Popular"
          },
          {
            "user_id": "user222",
            "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-09.1647603038.9821.jpg?fit=crop&auto=compress",
            "type": "rent",
            "location": "London",
            "address": "60 Westminster Avenue, London, SW1V",
            "rooms": 4,
            "bedrooms": 2,
            "bathrooms": 2,
            "size_sqft": 1400,
            "price": 2200
          },
          {
            "user_id": "user333",
            "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-08.1647603038.576.jpg?fit=crop&auto=compress",
            "type": "lease",
            "location": "London",
            "address": "80 Kensington Gardens, London, W2",
            "rooms": 5,
            "bedrooms": 3,
            "bathrooms": 2,
            "size_sqft": 1900,
            "price": 3800
          },
          {
            "user_id": "user444",
            "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/toyko-sky-tree.jpg",
            "type": "sale",
            "location": "Mumbai",
            "address": "234 Beachfront Road, Mumbai, MH",
            "rooms": 6,
            "bedrooms": 3,
            "bathrooms": 3,
            "size_sqft": 2000,
            "price": 1100000
          },
          {
            "user_id": "user555",
            "imageURL": "https://archello.com/thumbs/images/2022/03/18/tbs-10-c-randhir-singh.1647614802.6646.jpg?fit=crop&w=1260",
            "type": "rent",
            "location": "Mumbai",
            "address": "345 Hilltop Drive, Mumbai, MH",
            "rooms": 3,
            "bedrooms": 2,
            "bathrooms": 1,
            "size_sqft": 1000,
            "price": 25000,
            "category":"Popular"
          },
          {
            "user_id": "user666",
            "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Lotte%20World%20Tower%20-%20modlar_com.jpg",
                        "type": "lease",
            "location": "Mumbai",
            "address": "456 Lake Shore Road, Mumbai, MH",
            "rooms": 4,
            "bedrooms": 2,
            "bathrooms": 2,
            "size_sqft": 1200,
            "price": 28000
          },
          {
            "user_id": "user777",
            "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Makkah%20Royal%20Clock%20Tower.jpg",
            "type": "sale",
            "location": "New York",
            "address": "567 Riverfront Avenue, New York, NY",
            "rooms": 7,
            "bedrooms": 4,
            "bathrooms": 3,
            "size_sqft": 2400,
            "price": 1050000
          },
         {
                "user_id": "user888",
                "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-09.1647603038.9821.jpg?fit=crop&auto=compress",
                "type": "rent",
                "location": "New York",
                "address": "678 Parkside Drive, New York, NY",
                "rooms": 4,
                "bedrooms": 2,
                "bathrooms": 2,
                "size_sqft": 1400,
                "price": 2600
              },
              {
                "user_id": "user999",
                "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-08.1647603038.576.jpg?fit=crop&auto=compress",
                "type": "lease",
                "location": "New York",
                "address": "789 Riverside Lane, New York, NY",
                "rooms": 3,
                "bedrooms": 1,
                "bathrooms": 1,
                "size_sqft": 1100,
                "price": 3200,
                "category":"Popular"
              },
              {
                "user_id": "user121",
                "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/toyko-sky-tree.jpg",
                "type": "sale",
                "location": "London",
                "address": "70 Covent Garden Street, London, WC2E",
                "rooms": 6,
                "bedrooms": 3,
                "bathrooms": 2,
                "size_sqft": 1800,
                "price": 950000
              },
              {
                "user_id": "user232",
                "imageURL": "https://archello.com/thumbs/images/2022/03/18/tbs-10-c-randhir-singh.1647614802.6646.jpg?fit=crop&w=1260",
                "type": "rent",
                "location": "London",
                "address": "90 Mayfair Avenue, London, W1J",
                "rooms": 5,
                "bedrooms": 2,
                "bathrooms": 2,
                "size_sqft": 1600,
                "price": 2800
              },
              {
                "user_id": "user343",
                "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Lotte%20World%20Tower%20-%20modlar_com.jpg",
                "type": "lease",
                "location": "London",
                "address": "100 Piccadilly Road, London, SW1Y",
                "rooms": 4,
                "bedrooms": 2,
                "bathrooms": 1,
                "size_sqft": 1200,
                "price": 3500
              },
              {
                "user_id": "user454",
                "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/Makkah%20Royal%20Clock%20Tower.jpg",
                                "type": "sale",
                "location": "Mumbai",
                "address": "567 Seaside View, Mumbai, MH",
                "rooms": 5,
                "bedrooms": 3,
                "bathrooms": 2,
                "size_sqft": 1500,
                "price": 850000,
                "category":"Popular"
              },
              {
                "user_id": "user565",
                "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-09.1647603038.9821.jpg?fit=crop&auto=compress",
                "type": "rent",
                "location": "Mumbai",
                "address": "678 Hillcrest Lane, Mumbai, MH",
                "rooms": 4,
                "bedrooms": 2,
                "bathrooms": 1,
                "size_sqft": 1300,
                "price": 27000
              },
              {
                "user_id": "user676",
                "imageURL": "https://archello.com/thumbs/images/2022/03/18/25-best-architecture-firms-in-Delhi-08.1647603038.576.jpg?fit=crop&auto=compress",
                "type": "lease",
                "location": "Mumbai",
                "address": "789 Palm Grove Road, Mumbai, MH",
                "rooms": 3,
                "bedrooms": 1,
                "bathrooms": 1,
                "size_sqft": 950,
                "price": 20000
              },
              {
                "user_id": "user787",
                "imageURL": "https://img.staticmb.com/mbcontent/images/uploads/2022/3/toyko-sky-tree.jpg",
                "type": "sale",
                "location": "New York",
                "address": "890 Lakeside Drive, New York, NY",
                "rooms": 6,
                "bedrooms": 3,
                "bathrooms": 2,
                "size_sqft": 1900,
                "price": 980000,
                "category":"Popular"
              },
              {
                "user_id": "user898",
                "imageURL": "https://archello.com/thumbs/images/2022/03/18/tbs-10-c-randhir-singh.1647614802.6646.jpg?fit=crop&w=1260",
                "type": "rent",
                "location": "New York",
                "address": "901 Central Park Avenue, New York, NY",
                "rooms": 7,
                "bedrooms": 4,
                "bathrooms": 3,
                "size_sqft": 2200,
                "price": 3000
              }
          
        
      
    ]
  
    module.exports= propertie;
  